### ISSUE TITLE
Clarify whitespace interventions

### ISSUE THREAD

**Issue by AndydeCleyre** [Zren/plasma-applet-commandoutput#12]
I use this applet to display currently playing track information, and want to control the width, because if my panel changes size every few seconds it distracts me from work. So I use a monospace font, and implement a "resize" function, which pads the outside with spaces, or truncates the content.

The first problem is the auto-trimming (like Python's `str.strip`), but I work around that by adding some outer character, like `-` to either side.

That worked until I discovered I could color the content, using html-like markup (Qstring?). So for example, the script might alternately be outputting these two lines:

```html
<font color="#a94d37">-  The Beatles  -</font>
<font color="#a94d37">-I am the Walrus-</font>
```

Both strings are exactly the same length. The resulting presentation is colored. But the consecutive spaces are "squeezed" (even though they are not at the beginning or end of the string).

So the representation (colored) becomes:

```
- The Beatles -
-I am the Walrus-
```

They differ in size by two characters, because the consecutive spaces *in the middle of the string* have been reduced to a single space per grouping.

How can we prevent these interventions?

**Comment by Zren** [comment]
Use https://store.kde.org/p/998887/, though it seems opening that widget's config freezes plasma (infinite loop?) so if you want to edit it, open up the following file after installing it:

```
~/.local/share/plasma/plasmoids/org.kde.plasma.mediacontrollercompact/contents/ui/configGeneral.qml
```

Then add `id: pageColumn` to the first `ColumnLayout` and change `implicitWidth: mainColumn.implicitWidth` to `implicitWidth: pageColumn.implicitWidth`.

![2019-03-15___21-43-45](https://user-images.githubusercontent.com/416367/54469270-44ee0380-476c-11e9-90eb-7390e8867e8a.png)

Restart plasma with `killall plasmashell; kstart5 plasmashell` to reload the panel.

You can then open up `ExpandedRepresentation.qml` and delete the buttons. Basically delete the `Column { id: playerControls }` and everything after it.

![2019-03-15___21-49-25](https://user-images.githubusercontent.com/416367/54469330-13c20300-476d-11e9-808d-f19f0e4a9f54.png)

Just make sure you don't delete the final 3 closing tags.

![2019-03-15___21-52-57](https://user-images.githubusercontent.com/416367/54469369-80d59880-476d-11e9-8864-2bf9542f6186.png)

**Comment by Zren** [comment]
As for what actually controls the widget's width in a panel, the `Layout.preferredWidth: output.implicitWidth` in the `Plasmoid.fullRepresentation` item is what you need to look at.

Use `Layout.preferredWidth: 234`, or `Layout.preferredWidth: 234 * units.devicePixelRatio` if you want to code properly for HiDPI, will make it 234px wide.

https://github.com/Zren/plasma-applet-commandoutput/blob/master/package/contents/ui/main.qml#L94

**Comment by AndydeCleyre** [comment]
I don't think what you've suggested will function as well as what I have. My playback information falls back to information reported by Last.fm if no local players are found (so it is accurate even if some other device is playing the music). It also uses (IMO) reasonable and configurable ellipsis placement.

**Comment by AndydeCleyre** [comment]
Hey, it seems that if the new official color setting is used, white space is preserved!
