### ISSUE TITLE
Applet height in a vertical panel

### ISSUE THREAD

**Issue by ilkerhk** [Zren/plasma-applet-commandoutput#18]
Hi, 
I am using commandoutput on vertical panel.  
If the script output is more than 3 lines then the font becomes smaller than the font I set in the settings (keeping the total height about constant). I was wondering if there is any restriction for the height of the applet? 
 
I tried to unlock and configure panel and tried to increase the height of the applet but couldn't make it work. 
Thanks and keep up the nice work.

**Comment by Zren** [comment]
v10 should fixed this. I added a fixed height if you need it.

**Comment by ilkerhk** [comment]
It works nicely. Thank you for the quick solution and version release.
