### ISSUE TITLE
Where are the plasmoid configurations stored?

### ISSUE THREAD

**Issue by UtkarshVerma** [Zren/plasma-applet-commandoutput#20]
How can I back up the configurations for this plasmoid? I'm planning to put the related files under version control to passively track changes to the widget.

**Comment by Zren** [comment]
Your entire desktop layout is serialized to `~/.config/plasma-org.kde.plasma.desktop-appletsrc`

If you use eventcalendar, I wouldn't recommend making it public though as I put your login access token in that config.

**Comment by Zren** [comment]
You could use a script to read/write to another file 

```
value=`kreadconfig5 --file=$HOME/.config/plasma-org.kde.plasma.desktop-appletsrc --group=Containments --group=35 --group=Applets --group=60 --group=Configuration --group=General --key=command`
kwriteconfig5 --file=backup.ini --group=commandoutput --group=General --key=command "${value}"
```

**Comment by UtkarshVerma** [comment]
I guess I'll track the appletsrc for now since it doesnt contain any sensitive data. Thanks for the quick reply.
