### ISSUE TITLE
Widget size stability

### ISSUE THREAD

**Issue by Almtesh** [Zren/plasma-applet-commandoutput#22]
Hello,

I installed this widget on Plasma 5.18.5 on Kubuntu 20.04 and I have a problem on the size of the widget.
Every time the command executes, the widget can be resized randomly. Sometime, the new size makes the widget to put itself over or under another widget.
![Screenshot_20201005_214505](https://user-images.githubusercontent.com/8816946/95124736-28515c00-0754-11eb-86ec-72c4e88b9e91.png)
The text in this instance does not really change, but I can't get it smaller for a long time.

I saw in the code that there is an option to stabilise the size, but the option does not appear in the settings:
![Screenshot_20201005_214758](https://user-images.githubusercontent.com/8816946/95124917-76fef600-0754-11eb-91ae-60cb47fc159e.png)

**Comment by Almtesh** [comment]
I tryed to look at this code I don't know in a language I don't know, is my problem related to lines 189 to 199 property in package/content/ui/main.qml? I don't know what you mean in "FixedWidth".

**Comment by Zren** [comment]
Fixed width/height is hidden for desktop widgets as it sets `Layout.preferredWidth` which will set the width in the panel. For a desktop widget, `Layout.preferredWidth` is ignored. I don't set `Layout.maximumWidth` as it wasn't necessary.

What's probably happening is that your output has lots of extra spaces after the text before the newline?

Though I just tried it in manjaro. For some reason it wouldn't shrink smaller than this height at first. I could change the width no problem.

![2020-10-05___19-33-08](https://user-images.githubusercontent.com/416367/95142395-9b050c00-0741-11eb-87af-8a7c65363299.png)

After a few seconds I could shrink it a little bit smaller:

![2020-10-05___19-34-04](https://user-images.githubusercontent.com/416367/95142467-c556c980-0741-11eb-9118-d024caa5e3ed.png)

Then finally I could shrink it to:

![2020-10-05___19-35-16](https://user-images.githubusercontent.com/416367/95142538-e7e8e280-0741-11eb-9082-4e8a313687cf.png)

However after a few seconds it resized automatically to this. Probably after the command ran again and the text was updated.

![2020-10-05___19-35-45](https://user-images.githubusercontent.com/416367/95142562-f800c200-0741-11eb-826b-5017d3c610c0.png)

**Comment by Zren** [comment]
My guess is that `Text.implicitWidth` uses up as much width as possible if there's a newline. Perhaps I should use `Text.contentWidth`.

**Comment by Almtesh** [comment]
Surely, I don't know QML.
For info, my command is `upsc ups@nut-server | grep -E 'battery.charge:|input.frequency:|input.voltage:|output.frequency:|output.voltage:|ups.power:|ups.realpower:'`. When I execute is on a shell, I don't get extra spaces before new lines.

**Comment by Almtesh** [comment]
Actually, I think you might do two things:

1. add an option to disable widget auto-resize according to output's size.
1. improve the auto-resize.

**Comment by Almtesh** [comment]
Hello,

Do you need about that? I could try to get a look on it, if you want.

**Comment by Zren** [comment]
Sorry, I fixed it pretty quick, but wanted to test it overnight + after restarting and forgot about pushing the release. Should be fixed in v11.

**Comment by Almtesh** [comment]
I hate myself asking you that, but how can I install the new version? I can't find the updater.

**Comment by Zren** [comment]
If you go to "Add Widgets > Get New Widget > Download", the GUI should be able Update the widget. If that doesn't work (there's recently been a bug), then download the git repo and run:

```bash
kpackagetool --type=Plasma/Applet --upgrade ./package/
```

**Comment by Almtesh** [comment]
OK, thanks, widget updated and working as expected.
