### ISSUE TITLE
No French localization on version 11

### ISSUE THREAD

**Issue by Almtesh** [Zren/plasma-applet-commandoutput#26]
I installed the new version on my French desktop and I still get the texts in English.

When I go to the installation directory ($HOME/.local/share/plasma/plasmoids/com.github.zren.commandoutput), I don't get any *.mo file, I think that is the problem.

**Comment by Zren** [comment]
Did you install via `git`? If so you need to run `cd package/translate/ && sh ./build`

`commandoutput-v11-plasma5.12.plasmoid` has the `contents/locale/fr/LC_MESSAGES/plasma_applet_com.github.zren.commandoutput.mo` file, and it's what I uploaded to the KDE Store (https://store.kde.org/p/1166510/).

**Comment by Almtesh** [comment]
Sorry for the late answer.

I updated the plasmoid and I get the French localization now.  
I checked in the installation directory and I got the *.mo files.

So, I close the issue.
