### ISSUE TITLE
waitForCompletion is disabled?

### ISSUE THREAD

**Issue by trmdi** [Zren/plasma-applet-commandoutput#27]
Is this a typo?

https://github.com/Zren/plasma-applet-commandoutput/blob/9003024463e9e7cceaa07200da7ca0f10af27602/package/contents/ui/config/ConfigGeneral.qml#L45

I mean the option to make the timer runs only one time, in case the command does not need to update.

**Comment by Zren** [comment]
Kinda sorta. The executable data engine can't run the same command twice at the same time, so I disabled it. If the interval is shorter than the command takes to run, then I think it'll skip the 2nd call. But tbh that's nothing to worry about. I guess we can enable it.

**Comment by trmdi** [comment]
Hmm, when `Interval = 0`, it sill run only one time, even when `Timer.repeat == true`.
So, `waitForCompletion` is redundant for this purpose.

Though I don't know if it is still needed for other usages.

**Comment by Zren** [comment]
Might as well keep `waitForCompletion`. I may make limit the interval to 1ms if `waitForCompletion=false` though since it seems [QML Timer](https://doc.qt.io/qt-5/qml-qtqml-timer.html)'s will stop. Even `timer.restart()` like below doesn't seem to be working for some reason.

```
if (config.waitForCompletion || config.interval === 0) {
	timer.restart()
}
```

**Comment by trmdi** [comment]
Maybe this works?

[test.patch.txt](https://github.com/Zren/plasma-applet-commandoutput/files/5633723/test.patch.txt)

**Comment by Zren** [comment]
Your code is if `interval=0` then the timer doesn't repeat, nor does it "restart" when the command is finished. So the command will never be run more than once...

**Comment by trmdi** [comment]
Yes, we use interval=0 for making it run only one time intendedly.

**Comment by Zren** [comment]
Oh, you want a `runOnce` option?

**Comment by trmdi** [comment]
Yes, an example use case is just to write some texts on the desktop.

**Comment by Zren** [comment]
Do you really need it to be a "command", or do you basically want a "Note" widget?

**Comment by trmdi** [comment]
> Do you really need it to be a "command", or do you basically want a "Note" widget?

Hmm... Sometimes I want to write some texts on the dektop just to decorate it. :P
Like this: 
![image](https://user-images.githubusercontent.com/11857205/101187037-68ff2000-3686-11eb-8e2a-51144f7704bd.png)

The "Note" widget can't change the font family and size like this one.
Anyways, I can use a very large interval...

**Comment by Zren** [comment]
> I can use a very large interval.

Yeah, that's what I was about to suggest.

**Comment by trmdi** [comment]
Because when removing this, we could make the config window a bit simpler, but I don't know if there is any cons. Could you give an example in that `waitForCompletion == false` is useful?

**Comment by Zren** [comment]
A "clock" needs to update every 1000ms exactly. A clock running every 1010 seconds will skip a second every once and awhile.

I'm more likely to remove `waitForCompletion == true` than `== false`.

**Comment by trmdi** [comment]
I think you can't make a clock update at 0ms 1000ms 2000ms... (the real millisecond of the clock e.g. 10:45:02.000 AM -> 0ms...) exactly, it will update at e.g. 5ms 1235ms. 2001ms... randomly depending on when it starts, how long the command takes, the event loop... there will be always a delay between this clock and another. So I don't really understand your example. :/

**Comment by Zren** [comment]
There will always be a delay from X000ms, however I assume it should still start the logic around at X000ms. If there's a 100ms delay between restarting the timer, then you'll skip from 9s to 11s.

* 0ms
* 1100ms
* 2200ms
* 3300ms
* ...
* 9900ms
* 11000ms

Notice how it'll skip 10sec.

With a repeating timer, I assume the math when the timer is triggered would be the following to keep the timer attempting to trigger with the same interval between calls:

```
sleepFor(interval - ((now - timerStarted) % interval))
```

**Comment by trmdi** [comment]
Do you know why the output sometimes (1 time per minute) disappears when I use this command? The latest git version.
`[[ $((`date +%S` % 2)) -eq 0 ]] && echo "openSUSE KDE 😗" || echo "openSUSE KDE 😘"`
![image](https://user-images.githubusercontent.com/11857205/104707359-e1113900-574e-11eb-92c8-ff6635d9f552.png)
