### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by matthiasbeyer** [Zren/plasma-applet-commandoutput#32]
There is no license file in the repository.

CC https://github.com/NixOS/nixpkgs/pull/154485

**Comment by Zren** [comment]
Ah, looks like I was too lazy to add `X-KDE-PluginInfo-License=GPL` to the metadata. It shows the GPL license in the Widget Config > About > License.

**Comment by matthiasbeyer** [comment]
:smile: awesome, but I need to package it properly first, which I need the license for :laughing:

**Comment by Zren** [comment]
Same as win7 volume mixer and the rest of plasma should work. `license = licenses.gpl2Plus;`

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/plasma-applet-volumewin7mixer/default.nix#L25
