### ISSUE TITLE
Tooltip as option

### ISSUE THREAD

**Issue by specs32** [Zren/plasma-applet-commandoutput#42]
Hi.. 

An option to enable or disable the tooltip for this widget in form of a tick box in the General tab would be cool. !!
I am using it to display journalctl in the background of my secondary screen.. I really don't need the TT there ;)
Love the Widget !!
Greetings

![Screenshot_20230821_095122](https://github.com/Zren/plasma-applet-commandoutput/assets/15709095/11da2db3-459f-435a-83c2-5a29c7f8b7a9)

**Comment by aricaldeira** [comment]
I implemented a tooltip command (that can be empty) here:

https://github.com/Zren/plasma-applet-commandoutput/commit/c42431f7123a3f124a160a77df9401635933d036

**Comment by specs32** [comment]
I found a way to deactivate it in the source, but that option is really nice, thanks  !

**Comment by Zren** [comment]
PR #49 with @aricaldeira's tooltip command patches has been merged.
