### ISSUE TITLE
Plan to update for Plasma 6

### ISSUE THREAD

**Issue by Justinzobel** [Zren/plasma-applet-commandoutput#43]
I use this applet all day and it's great. If I may suggest you update the applet for Plasma 6 which is coming early next year. More info @ https://pointieststick.com/2023/10/24/its-time-to-port-your-widgets-to-plasma-6/

**Comment by geraldosimiao** [comment]
ohh I'm looking forward for this update.

**Comment by Zren** [comment]
I think I have to make a new product in the Plasma 6 category so:

https://www.pling.com/p/2136636/
