### ISSUE TITLE
Doesn't work on Plasma 6

### ISSUE THREAD

**Issue by lolren** [Zren/plasma-applet-commandoutput#47]
This widget is amazing. Will it get ported to plasma 6? regards

**Comment by guss77** [comment]
There's some work on Plasma 6 support in a fork at https://github.com/aricaldeira/plasma-applet-commandoutput

**Comment by adrianinsaval** [comment]
cool, how to get it installed? will they upload to the kde store?

**Comment by datWeazel** [comment]
> There's some work on Plasma 6 support in a fork at https://github.com/aricaldeira/plasma-applet-commandoutput

I tried the fork but I can't change the text colors. Is this a known issue?

**Comment by Zren** [comment]
@datWeazel use my master branch as it's merged the fork and fixed a few things. It probably wasn't tested when porting the ColorDialog to  Plasma6. It's harder to notice since it's a runtime bug.

It was this in the fork, however `currentColor` turned into `selectedColor` in Qt6.

```
onAccepted: {
	if (visible && color != currentColor) {
		colorField.text = currentColor
	}
}
```

Here's what it now is:  

https://github.com/Zren/plasma-applet-lib/commit/1e452aabd42d28ae72b41309e037ba3cfdd09844

**Comment by interknighterrant** [comment]
@Zren - Quick side comment, you are amazing... it wasn't until arch updated to plasma 6 how much I realized I use your widgets.  I use this command output and event calendar on every computer I own, really useful widgets and I thank you for making them.  Grateful they have been around and miss them already!

Back on topic...

I tried using the master branch from this repository and it won't build.  I notice the build script references a manifest.desktop file and that file is not present in this repository.  Maybe that has something to do with it.

I could make the fork at https://github.com/aricaldeira/plasma-applet-commandoutput build, but like previous comments indicate that fork has a runtime error where you can't change font color.  That fork did have a manifest.desktop file

If you get any time and have anything for me to try or any tips, I'm willing to try again to get it to build on Plasma 6 later.  Thanks again!

**Comment by Zren** [comment]
I'm not sure if I'm suppose to create a new project on the KDE Store under Plasma 6 Extensions or if I'm suppose to change the category of the existing product. For now I've made a new product.

https://www.pling.com/p/2136636/

Someday I'll test installing via the store in Plasma5.27 then copying the data to a Plasma6 VM to see what happens.
