### ISSUE TITLE
Adaptive size of input fields

### ISSUE THREAD

**Issue by thingsiplay** [Zren/plasma-applet-commandoutput#54]
Adapt size of the input fields when resizing the Command Output Settings window. Right now the line for the command is very short and would stay that short, even though there is enough room in the window. This becomes especially useful when the command is a chain of programs and many options.

**Comment by Zren** [comment]
Looks like I need to use `QQC2.TextField { wrapMode: QQC2.TextField.Wrap }`

https://doc.qt.io/qt-5/qml-qtquick-textinput.html#wrapMode-prop

Also I can use `Kirigami.FormData.isSection: true` to make the Kirigami entry use both columns however it still leaves a lot of empty whitespace on the sides.

**Comment by Zren** [comment]
![%Y-%M-%D___%H-%m-%S-1](https://github.com/Zren/plasma-applet-commandoutput/assets/416367/43d01289-535a-4c49-8602-d11c40dfc2ee)

The kirigami config theme can't grow very wide but it's better than what we currently have.

**Comment by Zren** [comment]
![%Y-%M-%D___%H-%m-%S-2](https://github.com/Zren/plasma-applet-commandoutput/assets/416367/fc506bc4-40b5-4191-b727-83bfcac50502)

Almost forgot the actions tab commands.

**Comment by thingsiplay** [comment]
Thanks for this. This is absolutely sufficient and makes it much better to edit directly in the edit box, instead copy/edit/copy/paste to external editor. This will be a nice update.
