### ISSUE TITLE
KDE 6.0.2: module "org.kde.plasma.components" version 2.0 is not installed

### ISSUE THREAD

**Issue by pfmiller0** [Zren/plasma-applet-commandoutput#55]
I just installed KDE 6.0.2 on OpenSUSE Tumbleweed and I am getting this error when trying to load the widget:

file:///home/USERNAME/.local/share/plasma/plasmoids/com.github.zren.commandoutput/contents/ui/main.qml:5:1: module "org.kde.plasma.components" version 2.0 is not installed

**Comment by Zren** [comment]
Sounds like you are using v12 for Plasma 5. You need v13 for Plasma 6.

* Plasma 5: https://store.kde.org/p/1166510/
* Plasma 6: https://store.kde.org/p/2136636/

**Comment by pfmiller0** [comment]
I did update to the Plasma 6 version before I saw this error, but eventually it went away. Possibly after I restarted my KDE session.

**Comment by quazgar** [comment]
> Possibly after I restarted my KDE session.

Same here, I needed to restart the KDE session for the error to go away, after installing the **Plasma 6** version.
