### ISSUE TITLE
Different outputs thermal on konsole vs plasma-applet-commandoutput

### ISSUE THREAD

**Issue by ghost** [Zren/plasma-applet-commandoutput#60]
Hello, i have this command:
`echo "$(cat /sys/class/thermal/thermal_zone*/temp | awk '{ print ($1 / 1000) "°" }' | cut -d$'\n' -f3-)"`

To display thermal temperature output on "plasma-applet-commandoutput", but strangely it gives me a different result from konsole.

![Screenshot_20240929_122906](https://github.com/user-attachments/assets/9bb5b0b9-5546-45b9-b1ff-7fea8d7acde4)

plasma-applet-commandoutput it is output constantly 10+ numbers ahead.

```
Operating System: openSUSE Tumbleweed 20240927
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Graphics Platform: Wayland
```
`plasma-applet-commandoutput (master)`

**Comment by Zren** [comment]
I only have `/sys/class/thermal/cooling_device*/` on my AMD 5600G + RX 6600, so can't confirm the exact issue with that command, however I can make a guess.

What is the output of: `cat /sys/class/thermal/thermal_zone*/temp` in both?

`| cut -d$'\n' -f3-` should grab lines... 3-EOF. If you have `termal_zone0`, `termal_zone1`, `termal_zone2`, `termal_zone3`, `termal_zone4` it'll show thermal zones 2-4.

The way that your terminal sorts these folders could be different compared to the bash implementation. Eg: Since I have 12 cooling devices, number 3 would be `cooling_device10` not `cooling_device2`.

```
/sys/class/thermal/cooling_device0/
/sys/class/thermal/cooling_device1/
/sys/class/thermal/cooling_device10/
/sys/class/thermal/cooling_device11/
/sys/class/thermal/cooling_device2/
/sys/class/thermal/cooling_device3/
/sys/class/thermal/cooling_device4/
/sys/class/thermal/cooling_device5/
/sys/class/thermal/cooling_device6/
/sys/class/thermal/cooling_device7/
/sys/class/thermal/cooling_device8/
/sys/class/thermal/cooling_device9/
```

Edit: Try adding the command without the `| cut` as a tooltip command.

**Comment by ghost** [comment]
Hi, Thanks for your help and clarification.

I should have added what i have
```
CPU - Intel(R) Core(TM) i7-10700 (8) @ 4.80 GHz
GPU - Intel UHD Graphics 630 @ 1.20 GHz [Integrated]
```

Request outputs

_Konsole_
```
$ cat /sys/class/thermal/thermal_zone*/temp
42000
27800
33000
```
_plasma-applet-commandoutput_
`42000`

I have another command which shows same results, but more "Human readable".

```
$ paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'

pch_cometlake  42.0°C
acpitz         27.8°C
x86_pkg_temp   33.0°C`
```
My first command output on the Konsole, from x86_pkg_temp, but it changes to "pch_cometlake" once i added to plasma-applet-commandoutput. At least that's how i understand it two different outputs.

My goal is to reach x86_pkg_temp.

**Comment by Zren** [comment]
Does `echo -e "42000\n27800\n33000\n"` work?

```bash
echo -e "42000\n27800\n33000\n" | awk '{ print($1 / 1000) "°" }' | cut -d$'\n' -f3
```

![2024-09-30___07-05-31](https://github.com/user-attachments/assets/1b49fd64-e7c5-4069-8f5c-137e5e0a2fb7)

**Comment by ghost** [comment]
It does output

```
$ echo -e "42000\n27800\n33000\n"
42000
27800
33000
```
```
$ echo -e "42000\n27800\n33000\n" | awk '{ print($1 / 1000) "°" }' | cut -d$'\n' -f3
33°
```
Just the degree 33° doesn't move.

**Comment by ghost** [comment]
Do you know a script or command that uses libksysguard, ksystemstats? I have impression that it should work better with these KDE tools.

**Comment by Zren** [comment]
With lm sensors:

```
❯ sensors amdgpu-pci-3000
amdgpu-pci-3000
Adapter: PCI adapter
vddgfx:        1.05 V  
vddnb:         1.09 V  
edge:         +37.0°C  
PPT:           9.00 W  
sclk:         400 MHz 
```

```bash
sensors amdgpu-pci-3000 | grep edge | tail -c16 | sed -e 's/ *//'
```

But personally I would skip the wildcard `*` instead of the number, and drop the cut command. Just figure out the hardcoded number for:

```bash
cat /sys/class/thermal/thermal_zone2/temp | awk '{ print ($1 / 1000) "°" }'
```

**Comment by ghost** [comment]
Thank you very much for your help and effort. With thermal numbers so far these are going to work on konsole.

thermal_zone0
thermal_zone1
thermal_zone2

```
$ cat /sys/class/thermal/thermal_zone0/temp | awk '{ print ($1 / 1000) "°" }'
40°
$ cat /sys/class/thermal/thermal_zone1/temp | awk '{ print ($1 / 1000) "°" }'
27.8°
$ cat /sys/class/thermal/thermal_zone2/temp | awk '{ print ($1 / 1000) "°" }'
33°
```

"thermal_zone2" output i want to use, so i put this one. But, once i add on Command Output Settings still output 40°,  It looks like switch to "thermal_zone0".

Edit: sensors brought more accurate results, i am going to use with sensors and close this issue as solved.
Thanks for your patience.

`sensors|grep Core|awk '{print $3}'|cut -b2,3,3|tail -1`
